#!/bin/bash

set -o errexit

MY_PROMPT='$ '
MY_YESNO_PROMPT='(y/n)$ '

grpname="flirimaging"
usrname=$USER
if [ 0"$SUDO_USER" = "0" ]; then
    usrname=$USER
else
    usrname=$SUDO_USER
fi
echo "username is $usrname"


if [ "$(id -u)" = "0" ]
then
    echo
    echo "This script will assist users in configuring their udev rules to allow";
    echo "access to USB devices. The script will create a udev rule which will";
    echo "add Flir USB devices to a group called $grpname. The user may also";
    echo "choose to restart the udev daemon. All of this can be done manually as well.";
    echo
    echo
else
    echo
    echo "This script needs to be run as root.";
    echo "eg.";
    echo "sudo spin-conf";
    echo
    exit 0
fi

echo
echo "------------Add user $usrname to group $grpname.";

groupadd -f $grpname
usermod -a -G $grpname $usrname

UdevFile="/etc/udev/rules.d/40-flir-spinnaker.rules";
echo
echo "Writing the udev rules file.";
echo "SUBSYSTEM==\"usb\", ATTRS{idVendor}==\"1e10\", GROUP=\"$grpname\"" >> $UdevFile

/etc/init.d/udev restart

echo
echo "Configuration complete. A reboot may be required on some systems for changes to take effect";
echo

exit 0
